In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [3]:
df=pd.read_csv("train.csv",usecols=['Age','Fare','Survived'])

In [4]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
x_train

Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [11]:
si=SimpleImputer()  #by default all missing values replace by mean
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [33]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [34]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [35]:
mi=MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [36]:
mi.features_   #indicate index 0 column contain missing value

array([0], dtype=int64)

In [37]:
x_train_missing=mi.transform(x_train)
x_test_missing=mi.transform(x_test)

In [38]:
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [39]:
x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [40]:
x_train['Age_NA']=x_train_missing
x_test['Age_NA']=x_test_missing

In [41]:
x_train.sample(5)

Age     Fare  Age_NA
744  31.0   7.9250   False
684  60.0  39.0000   False
176   NaN  25.4667    True
260   NaN   7.7500    True
512  36.0  26.2875   False

In [42]:
si=SimpleImputer()  #by default all missing values replace by mean
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [44]:
## Accuracy get increase after missing indicator

from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred=clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173

In [48]:
# Here i use add indicator it directly add missing indicator
#no need to use MissingIndicator class
si=SimpleImputer(add_indicator=True)   
x_train_trf3=si.fit_transform(x_train)
x_test_trf3=si.transform(x_test)

In [49]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train_trf3,y_train)
y_pred=clf.predict(x_test_trf3)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173